import MainContainer from "@/modules/layout/MainContainer";
import Navbar from "@/modules/layout/Navbar.client";
import Topbar from "@/modules/layout/Topbar.client";
import ToastProvider from "@/shared/Toast.client";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable}`}
      lang="en"
      suppressHydrationWarning
    >
      <body className="bg-background text-text flex h-dvh w-full flex-col antialiased">
        <ThemeProvider attribute="class">
          <ToastProvider>
            <Topbar />
            <div className="flex h-96 w-full grow">
              <Navbar />
              <MainContainer>{children}</MainContainer>
            </div>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
